--  File created - Tuesday-November-03-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CARRIER
--------------------------------------------------------

  CREATE TABLE "USERNAME"."CARRIER" 
   (	"CARRIERID" NUMBER(30,0), 
	"CONTACTNAME" VARCHAR2(30 BYTE), 
	"PHONE" NUMBER(10,0), 
	"CARRIER_COMPANY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "USERNAME"."CUSTOMER" 
   (	"CUSTOMER_ID" NUMBER(30,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" NUMBER(10,0), 
	"ADRESS" VARCHAR2(30 BYTE), 
	"BILLING_COUNTRY" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Table ONE_ORDER
--------------------------------------------------------

  CREATE TABLE "USERNAME"."ONE_ORDER" 
   (	"ORDERID" NUMBER(10,0), 
	"CUSTOMER_ID" NUMBER(30,0), 
	"PRODUCT_ID" NUMBER(30,0), 
	"PAYMENT_ID" NUMBER(30,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "USERNAME"."ORDERS" 
   (	"ORDER_DATE" DATE, 
	"ORDERID" NUMBER(10,0), 
	"SHIP_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "USERNAME"."PAYMENT" 
   (	"CUSTOMER_ID" NUMBER(30,0), 
	"PAYMENT_ID" NUMBER(30,0), 
	"ORDER_ID" NUMBER(30,0), 
	"PAYMENT_TYPE" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "USERNAME"."PRODUCTS" 
   (	"SUPPLIERID" VARCHAR2(30 BYTE), 
	"PRODUCTID" VARCHAR2(30 BYTE), 
	"PRICE" NUMBER(6,0), 
	"PRODUCT_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "USERNAME"."SUPPLIER" 
   (	"SUPPLIERID" VARCHAR2(30 BYTE), 
	"COMPANY" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(40 BYTE), 
	"TYPEOFGOOD" VARCHAR2(30 BYTE), 
	"COMPANYNAME" VARCHAR2(40 BYTE), 
	"PHONE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
REM INSERTING into USERNAME.CARRIER
SET DEFINE OFF;
Insert into USERNAME.CARRIER (CARRIERID,CONTACTNAME,PHONE,CARRIER_COMPANY) values (1,'Jon',647823232,'Fedex');
Insert into USERNAME.CARRIER (CARRIERID,CONTACTNAME,PHONE,CARRIER_COMPANY) values (2,'Alex',647822234,'DHL');
Insert into USERNAME.CARRIER (CARRIERID,CONTACTNAME,PHONE,CARRIER_COMPANY) values (3,'Mike',647823632,'UPS');
REM INSERTING into USERNAME.CUSTOMER
SET DEFINE OFF;
Insert into USERNAME.CUSTOMER (CUSTOMER_ID,NAME,PHONE,ADRESS,BILLING_COUNTRY) values (1,'Jon',6477451234,'65 somewhere blvd.','Serbia');
Insert into USERNAME.CUSTOMER (CUSTOMER_ID,NAME,PHONE,ADRESS,BILLING_COUNTRY) values (2,'Mychaylo',4164560982,'8 church st.','Serbia');
Insert into USERNAME.CUSTOMER (CUSTOMER_ID,NAME,PHONE,ADRESS,BILLING_COUNTRY) values (3,'Atal',6476097517,'5 lakeridge dr.','Afghanistan');
REM INSERTING into USERNAME.ONE_ORDER
SET DEFINE OFF;
Insert into USERNAME.ONE_ORDER (ORDERID,CUSTOMER_ID,PRODUCT_ID,PAYMENT_ID) values (1,1,1,1);
REM INSERTING into USERNAME.ORDERS
SET DEFINE OFF;
Insert into USERNAME.ORDERS (ORDER_DATE,ORDERID,SHIP_DATE) values (to_date('20-FEB-15','DD-MON-RR'),1,to_date('22-FEB-15','DD-MON-RR'));
REM INSERTING into USERNAME.PAYMENT
SET DEFINE OFF;
Insert into USERNAME.PAYMENT (CUSTOMER_ID,PAYMENT_ID,ORDER_ID,PAYMENT_TYPE) values (1,1,1,'CIBC');
REM INSERTING into USERNAME.PRODUCTS
SET DEFINE OFF;
Insert into USERNAME.PRODUCTS (SUPPLIERID,PRODUCTID,PRICE,PRODUCT_NAME) values ('2','1',240,'Play Station 4');
Insert into USERNAME.PRODUCTS (SUPPLIERID,PRODUCTID,PRICE,PRODUCT_NAME) values ('2','2',40,'Cooking Pot');
Insert into USERNAME.PRODUCTS (SUPPLIERID,PRODUCTID,PRICE,PRODUCT_NAME) values ('2','3',140,'Baby Crib');
REM INSERTING into USERNAME.SUPPLIER
SET DEFINE OFF;
Insert into USERNAME.SUPPLIER (SUPPLIERID,COMPANY,ADDRESS,TYPEOFGOOD,COMPANYNAME,PHONE) values ('3','Nike','36 queen st.','Electronics Store','idk3',9052121485);
Insert into USERNAME.SUPPLIER (SUPPLIERID,COMPANY,ADDRESS,TYPEOFGOOD,COMPANYNAME,PHONE) values ('1','Sirens','15 road Dr.','Clothing','idk1',4167653412);
Insert into USERNAME.SUPPLIER (SUPPLIERID,COMPANY,ADDRESS,TYPEOFGOOD,COMPANYNAME,PHONE) values ('2','Wall Mart','76 crack Dr.','Department Store','idk2',9056765419);
Insert into USERNAME.SUPPLIER (SUPPLIERID,COMPANY,ADDRESS,TYPEOFGOOD,COMPANYNAME,PHONE) values ('5','Test','15 road Dr.','Clothing','idk',4167653412);
--------------------------------------------------------
--  DDL for Index ORDERID
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERNAME"."ORDERID" ON "USERNAME"."ONE_ORDER" ("ORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
--------------------------------------------------------
--  Constraints for Table ONE_ORDER
--------------------------------------------------------

  ALTER TABLE "USERNAME"."ONE_ORDER" ADD CONSTRAINT "ORDERID" PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
 
  ALTER TABLE "USERNAME"."ONE_ORDER" MODIFY ("ORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "USERNAME"."PRODUCTS" MODIFY ("SUPPLIERID" NOT NULL ENABLE);
 
  ALTER TABLE "USERNAME"."PRODUCTS" ADD PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARRIER
--------------------------------------------------------

  ALTER TABLE "USERNAME"."CARRIER" ADD PRIMARY KEY ("CARRIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "USERNAME"."PAYMENT" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERNAME"."PAYMENT" ADD PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "USERNAME"."SUPPLIER" MODIFY ("COMPANY" NOT NULL ENABLE);
 
  ALTER TABLE "USERNAME"."SUPPLIER" ADD PRIMARY KEY ("SUPPLIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "USERNAME"."CUSTOMER" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ONE_ORDER
--------------------------------------------------------

  ALTER TABLE "USERNAME"."ONE_ORDER" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "USERNAME"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "USERNAME"."ORDERS" ADD CONSTRAINT "FK" FOREIGN KEY ("ORDERID")
	  REFERENCES "USERNAME"."ONE_ORDER" ("ORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "USERNAME"."PAYMENT" ADD FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "USERNAME"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
 
  ALTER TABLE "USERNAME"."PAYMENT" ADD FOREIGN KEY ("ORDER_ID")
	  REFERENCES "USERNAME"."ONE_ORDER" ("ORDERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "USERNAME"."PRODUCTS" ADD FOREIGN KEY ("SUPPLIERID")
	  REFERENCES "USERNAME"."SUPPLIER" ("SUPPLIERID") ENABLE;

